#########################################
### Base Image                         ##
#########################################
FROM node:14
RUN apt-get update && apt install libcurl4-gnutls-dev default-jdk -y && apt autoremove -y

COPY . /app
WORKDIR /app

RUN npm install && npm run build --if-present
CMD npm test